"""Create database

Revision ID: 8c729922caa6
Revises: 
Create Date: 2023-11-25 00:24:18.041238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c729922caa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('passport', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('family_status', sa.String(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('adress', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_number', sa.String(), nullable=False),
    sa.Column('circle_name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('group_number', sa.String(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['Circle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('school_number', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('birthday_certificate_information', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('home_phone', sa.String(), nullable=False),
    sa.Column('parents_information', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transition_date', sa.String(), nullable=False),
    sa.Column('group_id_from', sa.Integer(), nullable=True),
    sa.Column('group_id_to', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.String(), nullable=False),
    sa.Column('date_finish', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id_from'], ['Party.id'], ),
    sa.ForeignKeyConstraint(['group_id_to'], ['Party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transition')
    op.drop_table('Children')
    op.drop_table('Party')
    op.drop_table('Circle')
    op.drop_table('Teacher')
    # ### end Alembic commands ###
