"""Update transition model

Revision ID: 7f8f9da266a2
Revises: 702e4e84f87d
Create Date: 2023-12-01 14:47:26.892917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8f9da266a2'
down_revision: Union[str, None] = '702e4e84f87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transition', sa.Column('children_id', sa.Integer(), nullable=True))
    op.alter_column('Transition', 'group_id_from',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('Transition_group_id_from_fkey', 'Transition', type_='foreignkey')
    op.create_foreign_key(None, 'Transition', 'Children', ['children_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transition', type_='foreignkey')
    op.create_foreign_key('Transition_group_id_from_fkey', 'Transition', 'Party', ['group_id_from'], ['id'])
    op.alter_column('Transition', 'group_id_from',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Transition', 'children_id')
    # ### end Alembic commands ###
